### ISSUE TITLE
Update tslint:recommended configuration for 4.0 release

### ISSUE THREAD

**Issue by adidahiya** [palantir/tslint#1507]
#Let's track the breaking changes we want to make to the `tslint:recommended` config here.
- [ ] TODO: list of changes
  - [x] **deprecate** `no-unused-variable` #1618 
  - [x] **remove** `no-duplicate-key` #885 
  - [x] **remove** `label-undefined` #877 
  - [x] **remove** `use-strict` #678 
  - [x]  **remove** `no-unreachable` #661 
  - [ ] **add** `no-unsafe-finally`
  - [ ] **add** `ordered-imports`
    - compared to current `tslint:latest`, we want to **change** the `named-imports-order` option to `"case-insensitive"`
  - [ ] **add** new ones from #1506 
  - [ ] **add** `max-classes-per-file`
  - [ ] **add** `prefer-for-of`
  - [ ] **add** `array-type`
  - [ ] **add** `adjacent-overload-signatures`
  - [ ] **add** `object-literal-key-quotes`
  - [ ] **add** `object-literal-shorthand`?
  - [ ] **add** `only-arrow-functions`/`allow-declarations`

---

Also, I was thinking it might be useful for users to have access to an older stable configuration so that they don't have to address all of 4.0's breaking changes at once. Perhaps a new config called `tslint:3.x` that is identical to the current `tslint:latest`?

**Comment by nchen63** [comment]
@adidahiya It looks like you changed `no-unused-variable` to deprecated already. I assume you didn't remove it since people need to turn on the compile flag

**Comment by nchen63** [comment]
added some more from latest.ts:

 add adjacent-overload-signatures
 add object-literal-key-quotes
 add object-literal-shorthand?
 add only-arrow-functions/allow-declarations

**Comment by adidahiya** [comment]
yep, I'm sure about object-literal-shorthand

**Comment by zhaytee** [comment]
Hey folks, trying out 4.0.0-dev.1 here. Very simple config and invocation:
`tslint.json:
{
  "extends": "tslint:recommended"
}`

`invocation:
$ node_modules/.bin/tslint -e "node_modules" "src/**/*.js"`

I keep running into the following error:
`Could not find implementations for the following rules specified in the configuration: no-duplicate-key`

I grepped for that rule name, and it seems to be defined as part of the `recommended` set of rules. But the rule itself is no longer included with tslint, is that correct?

**Comment by nchen63** [comment]
@zhaytee it was removed with #1671, which didn't make it into 4.0.0-dev.1. Not sure why the rule appeared removed

**Comment by zhaytee** [comment]
@nchen63 Thanks for your reply. I `rm -rf`'d my node_modules dir and did a fresh `yarn install`, making sure that 4.0.0-dev.1 was being pulled down. Indeed, 4.0.0-dev.1 is the version installed, yet I'm still seeing the error message about `no-duplicate-key` not being found. See the attached screenshot for details.

Also, the error still goes away when I edit `tslint/lib/configs/recommended.js` and set `no-duplicate-key` to false. Not sure what's up. Happy to provide any more information if need be!

<img width="717" alt="screen shot 2016-11-11 at 7 07 03 pm" src="https://cloud.githubusercontent.com/assets/43938/20235292/db7c403a-a842-11e6-938e-907fcf0e5877.png">

**Comment by nchen63** [comment]
@zhaytee You're right. I looked at the tag for dev.1, and it does reflect what you're seeing. Thanks for looking into this. dev.2 should be out soonish
